[package]
name = "noop-executor"
version = "0.1.2"
edition = "2024"
description = "No-op executors for async tasks"
repository = "https://github.com/raviqqe/noop-executor"
license = "Unlicense"

[dependencies]
